# docker compose up -d

services:
  app:
    build:
      context: .
      dockerfile: ./Containerfile
    volumes:
      - ./:/srv:Z,cached
    command: sleep infinity

  db:
    image: "postgres:16.3"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data:
