services:
  app:
    build:
      context: ..
      dockerfile: ./.devcontainer/Containerfile
    volumes:
      - ../..:/srv:Z,cached
    command: sleep infinity

  db:
    image: "postgres:16.3"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
