FROM docker.io/elixir:1.17-alpine

# Install system dependencies & common dev tools
RUN apk update \
  && apk upgrade \
  && apk add \

  # PostgreSQL client for Database access
  postgresql-client \

  # Node.js for compiling front-end assets
  nodejs-current \
  npm \

  # Git for version control
  git \

  # Shellcheck for linting shell scripts
  shellcheck \

  # inotify-tools for file watching
  inotify-tools \

  # Common utilities
  bash \
  curl \
  gnupg \

  # Timezone data
  tzdata

ENV GIT_EDITOR="code --wait"

# Set up non-root user
RUN adduser -D -g '' -s bash vscode
USER vscode
WORKDIR /workspaces

COPY .devcontainer/scripts/bash_theme_snippet.sh /home/vscode/.bashrc

# Install Phoenix
RUN mix local.hex --force \
  && mix archive.install hex phx_new --force
