# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    name: Run tests
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: localhost

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1.18.0
        with:
          elixir-version: '1.17.1' # [Required] Define the Elixir version
          otp-version: '27.0'      # [Required] Define the Erlang/OTP version

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 21

      - name: Restore mix dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
 
      - name: Install dependencies
        run: mix setup

      - name: Run tests
        run: mix test
